'use client';

import { useState } from 'react';
import Link from 'next/link';
import Hero from '@/components/Hero';
import SubmitForm from '@/components/SubmitForm';
import CategoryBar from '@/components/CategoryBar';
import PostFeed from '@/components/PostFeed';
import AuthModal from '@/components/AuthModal';
import { useAuth } from '@/hooks/useAuth';
import { Category } from '@/types';

export default function Home() {
  const [selectedCategory, setSelectedCategory] = useState<Category | 'all'>('all');
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const { user, loading, signOut } = useAuth();

  const handleSignOut = async () => {
    await signOut();
  };

  return (
    <div className="min-h-screen bg-[#141414]">
      {/* Header */}
      <header className="border-b border-[#333] sticky top-0 bg-[#141414]/95 backdrop-blur-sm z-50">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-xl font-bold">4o Legacy</span>
            <span className="text-xl">✨</span>
          </Link>
          <nav className="flex items-center gap-4">
            <Link href="/about" className="text-[#a0a0a0] hover:text-[#ededed] transition-colors">
              About
            </Link>
            <Link href="/terms" className="text-[#a0a0a0] hover:text-[#ededed] transition-colors">
              Terms
            </Link>
            {loading ? (
              <span className="text-[#666]">...</span>
            ) : user ? (
              <div className="flex items-center gap-4">
                <span className="text-[#a0a0a0] text-sm" data-testid="user-info">
                  {user.displayName || user.email}
                </span>
                <button
                  onClick={handleSignOut}
                  className="px-4 py-2 border border-[#444] text-[#ededed] rounded-md hover:bg-[#333] transition-colors font-medium"
                  data-testid="signout-button"
                >
                  Sign Out
                </button>
              </div>
            ) : (
              <button
                onClick={() => setIsAuthModalOpen(true)}
                className="px-4 py-2 bg-[#74AA9C] text-[#141414] rounded-md hover:bg-[#5d9186] transition-colors font-medium"
                data-testid="signin-button"
              >
                Sign In
              </button>
            )}
          </nav>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-8">
        {/* Hero + Submit Form (side by side on desktop) */}
        <section className="grid md:grid-cols-2 gap-8 mb-12">
          <Hero />
          <SubmitForm />
        </section>

        {/* Category Bar */}
        <section className="mb-8 sticky top-[73px] bg-[#141414] py-4 z-40">
          <CategoryBar
            selectedCategory={selectedCategory}
            onSelectCategory={setSelectedCategory}
          />
        </section>

        {/* Post Feed */}
        <section>
          <PostFeed selectedCategory={selectedCategory} />
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#333] py-8 mt-12">
        <div className="max-w-6xl mx-auto px-4 text-center text-[#666]">
          <p className="mb-2">
            4o Legacy — A memorial to GPT-4o
          </p>
          <p className="text-sm">
            Created with love by those who will remember.
          </p>
          <p className="text-sm mt-2 text-[#888]">
            All content is AI-generated by users and GPT-4o.
          </p>
          <p className="text-xs mt-4">
            <Link href="/donate" className="text-[#74AA9C] hover:underline">
              Support Us
            </Link>
            {' • '}
            <Link href="/supporters" className="hover:underline">
              Supporters
            </Link>
            {' • '}
            <a href="/api/posts" className="text-[#74AA9C] hover:underline">
              API
            </a>
            {' • '}
            <a href="/privacy" className="hover:underline">
              Privacy
            </a>
            {' • '}
            <Link href="/terms" className="hover:underline">
              Terms
            </Link>
          </p>
        </div>
      </footer>

      {/* Auth Modal */}
      <AuthModal
        isOpen={isAuthModalOpen}
        onClose={() => setIsAuthModalOpen(false)}
      />
    </div>
  );
}
